### ISSUE TITLE
Less verbose output

### ISSUE THREAD

**Issue by Lp0lp** [MikkelDA/CGSB#2]
Heyo! Perhaps I missed it, but an option to have a more silent/less verbose output would be great. Maybe keep the detailed output details in the log file only?

**Comment by MikkelDA** [comment]
The only ways to reduce verboseness right now is by using either:
quiet = True # Removes all terminal prints
or
extra = False # Removes the composition tables that are printed for membranes and solvents

I am currently working on a more rigid verboseness setting which will likely be implemented this week along with some other changes.

**Comment by MikkelDA** [comment]
The newest version has a "verbose" command such that it can be controlled a bit more easily. 
Simply use: "verbose = number" where the number can be between 0 and 6, with 6 giving the most verbose printout and 0 the least verbose. The verboseness does not affect what is written to the .log file.
